'''title'''
__title__ = 'pppytools'
'''description'''
__description__ = 'Pytools: Some useful tools written by pure python.'
'''url'''
__url__ = 'https://github.com/Carpp/pytools'
'''version'''
__version__ = '0.1.14'
'''author'''
__author__ = 'Car'
'''email'''
__email__ = 'Carblwx@gmail.com'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Copyright 2021 Car'
